extraVolumeMounts:
  - name: configfile
    mountPath: /app/config
extraVolumes:
  - name: configfile
    emptyDir: {}
initContainers:
  - name: init-clone-repo
    imagePullPolicy: Always
    image: alpine/git
    args:
      - clone
      - 'https://github.com/attiferosisal/apachepod-with-initcontainer.git'
      - '/tmp/'
    env:
      - name: GIT_USERNAME
        valueFrom:
          secretKeyRef:
            key: username
            name: test-secret
      - name: GIT_PASSWORD
        valueFrom:
          secretKeyRef:
            key: password
            name: test-secret
    volumeMounts:
      - name: configfile
        mountPath: /custom-tools