extraVolumeMounts:
  - name: configfile
    mountPath: /app/config
extraVolumes:
  - name: gitfile
    emptyDir: {}
  - name: configfile
    emptyDir: {}
initContainers:
  - name: init-clone-repo
    imagePullPolicy: Always
    image: alpine/git
    args:
      - clone
      - https://github.com/attiferosisal/apachepod-with-initcontainer.git
      - /gitfile
    volumeMounts:
      - name: gitfile
        mountPath: /gitfile
  - name: init-copy-file
    imagePullPolicy: Always
    image: alpine
    command: [ "/bin/sh","-c", "cp /gitfile/* /configfile/" ]
    volumeMounts:
      - name: gitfile
        mountPath: /gitfile
      - name: configfile
        mountPath: /configfile